apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-chart.fullname" . }}
  labels:
    {{- include "base-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pod.replicas | default 1 }}
  {{- with .Values.pod.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  {{- with .Values.pod.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ . }}
  {{- end }}
  {{- with .Values.pod.progressDeadlineSeconds }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "base-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "base-chart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.pod.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "base-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.pod.podSecurityContext | nindent 8 }}
      {{- if .Values.pod.volumes }}
      volumes:
        {{- toYaml .Values.pod.volumes | nindent 8 }}
      {{- end }}
      {{- include "mapper.containers" . | nindent 6 }}
      {{- with .Values.pod.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pod.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.pod.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.pod.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
